package battleship_gui;

import java.awt.Color;
import java.util.List;


/**
 *
 * @author John Decker
 */
public class TextInputs extends javax.swing.JFrame {
    
    RegExCheck validate = new RegExCheck();
    PlayerInfoQueries playerQueries;
    private List<PlayerInfo> results;
    private int numberOfEntries = 0;
    Color correct = new Color(102,255,102);
    Color wrong = new Color(255,102,102);
    JFrame_Battleship game;

    /**
     * Creates new form TextInputs
     */
    public TextInputs() {
        initComponents();
        playerQueries = new PlayerInfoQueries();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        setTitle("Sign Up or Login");
        this.requestFocusInWindow();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSignUpLogin = new javax.swing.JPanel();
    invalidUsername = new javax.swing.JInternalFrame();
    checkMarkIconLabel = new javax.swing.JLabel();
    checkMessageLabel = new javax.swing.JLabel();
    doneButton2 = new javax.swing.JButton();
    left_panel = new javax.swing.JPanel();
    registerButton = new javax.swing.JButton();
    lastNameField = new javax.swing.JTextField();
    emailErrorLabel = new javax.swing.JLabel();
    signUpLabel = new javax.swing.JLabel();
    passwordErrorLabel = new javax.swing.JLabel();
    usernameErrorLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JTextField();
    emailField = new javax.swing.JTextField();
    usernameField = new javax.swing.JTextField();
    checkButton = new javax.swing.JButton();
    firstNameField = new javax.swing.JTextField();
    signInButton = new javax.swing.JButton();
    usernameNotFoundErrorLabel = new javax.swing.JLabel();
    usernameField2 = new javax.swing.JTextField();
    passwordField2 = new javax.swing.JTextField();
    loginLabel = new javax.swing.JLabel();
    smallbackgroundImageLabel = new javax.swing.JLabel();
    right_panel = new javax.swing.JPanel();
    jInvalidUsername = new javax.swing.JLayeredPane();
    smallbackgroundImageLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImages(null);

    jSignUpLogin.setMinimumSize(new java.awt.Dimension(640, 461));
    jSignUpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    invalidUsername.setTitle("Username Availability");
    invalidUsername.setFrameIcon(null);
    invalidUsername.setVisible(false);

    checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/exclamation_point_100x100.png"))); // NOI18N

    checkMessageLabel.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
    checkMessageLabel.setText("Username is unavailable");

    doneButton2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
    doneButton2.setText("done");
    doneButton2.setFocusable(false);
    doneButton2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        doneButton2MouseClicked(evt);
      }
    });

    javax.swing.GroupLayout invalidUsernameLayout = new javax.swing.GroupLayout(invalidUsername.getContentPane());
    invalidUsername.getContentPane().setLayout(invalidUsernameLayout);
    invalidUsernameLayout.setHorizontalGroup(
      invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(invalidUsernameLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkMarkIconLabel)
        .addGroup(invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addComponent(checkMessageLabel))
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(130, 130, 130)
            .addComponent(doneButton2)))
        .addContainerGap(29, Short.MAX_VALUE))
    );
    invalidUsernameLayout.setVerticalGroup(
      invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(invalidUsernameLayout.createSequentialGroup()
        .addGroup(invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(checkMarkIconLabel))
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(checkMessageLabel)
            .addGap(18, 18, 18)
            .addComponent(doneButton2)))
        .addContainerGap(41, Short.MAX_VALUE))
    );

    jSignUpLogin.add(invalidUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 480, 200));

    left_panel.setOpaque(false);
    left_panel.setPreferredSize(new java.awt.Dimension(339, 511));

    registerButton.setBackground(new java.awt.Color(102, 102, 102));
    registerButton.setForeground(new java.awt.Color(204, 204, 204));
    registerButton.setText("Register");
    registerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
    registerButton.setPreferredSize(new java.awt.Dimension(80, 40));
    registerButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseMoved(java.awt.event.MouseEvent evt) {
        registerButtonMouseMoved(evt);
      }
    });
    registerButton.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        registerButtonFocusLost(evt);
      }
    });
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        registerButtonMouseClicked(evt);
      }
    });

    lastNameField.setText("Last name");
    lastNameField.setPreferredSize(new java.awt.Dimension(200, 30));
    lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        lastNameFieldFocusLost(evt);
      }
    });

    emailErrorLabel.setVisible(false);
    emailErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    emailErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    emailErrorLabel.setText("Please enter valid email address\n");

    signUpLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
    signUpLabel.setForeground(new java.awt.Color(204, 204, 204));
    signUpLabel.setText("Sign Up");

    passwordErrorLabel.setVisible(false);
    passwordErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    passwordErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    passwordErrorLabel.setText("At least1 uppercase, 1 lowercase, 1 numeric, 8 - 15 chars.");

    usernameErrorLabel.setVisible(false);
    usernameErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    usernameErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    usernameErrorLabel.setText("Must contain 1 lowercase, 4 - 10 chars");
    usernameErrorLabel.setToolTipText("");

    passwordField.setText("Password");
    passwordField.setPreferredSize(new java.awt.Dimension(200, 30));
    passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        passwordFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        passwordFieldFocusLost(evt);
      }
    });
    passwordField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        passwordFieldActionPerformed(evt);
      }
    });

    emailField.setText("Email address");
    emailField.setPreferredSize(new java.awt.Dimension(200, 30));
    emailField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        emailFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        emailFieldFocusLost(evt);
      }
    });

    usernameField.setText("Username");
    usernameField.setPreferredSize(new java.awt.Dimension(200, 30));
    usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        usernameFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        usernameFieldFocusLost(evt);
      }
    });

    checkButton.setBackground(new java.awt.Color(102, 102, 102));
    checkButton.setForeground(new java.awt.Color(204, 204, 204));
    checkButton.setText("check");
    checkButton.setToolTipText("Check availablility");
    checkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    checkButton.setPreferredSize(new java.awt.Dimension(80, 40));
    checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        checkButtonMouseClicked(evt);
      }
    });

    firstNameField.setText("First name");
    firstNameField.setPreferredSize(new java.awt.Dimension(200, 30));
    firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        firstNameFieldFocusLost(evt);
      }
    });

    javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
    left_panel.setLayout(left_panelLayout);
    left_panelLayout.setHorizontalGroup(
      left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
      .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(left_panelLayout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(60, 60, 60)
              .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(48, 48, 48)
              .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(48, 48, 48)
              .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(emailErrorLabel))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(usernameErrorLabel))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(0, 0, 0)
              .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(passwordErrorLabel)
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(100, 100, 100)
              .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    left_panelLayout.setVerticalGroup(
      left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 510, Short.MAX_VALUE)
      .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(left_panelLayout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(25, 25, 25)
          .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(18, 18, 18)
          .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(7, 7, 7)
          .addComponent(emailErrorLabel)
          .addGap(4, 4, 4)
          .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(10, 10, 10)
          .addComponent(usernameErrorLabel)
          .addGap(4, 4, 4)
          .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(10, 10, 10)
          .addComponent(passwordErrorLabel)
          .addGap(4, 4, 4)
          .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(10, 10, 10)
          .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    jSignUpLogin.add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 400, 510));
    left_panel.setVisible(true);

    signInButton.setBackground(new java.awt.Color(102, 102, 102));
    signInButton.setForeground(new java.awt.Color(204, 204, 204));
    signInButton.setText("Sign in");
    signInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    signInButton.setPreferredSize(new java.awt.Dimension(70, 40));
    signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        signInButtonMouseClicked(evt);
      }
    });
    jSignUpLogin.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, -1));

    usernameNotFoundErrorLabel.setVisible(false);
    usernameNotFoundErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    usernameNotFoundErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    usernameNotFoundErrorLabel.setText("Username not found! Please sign up.");
    jSignUpLogin.add(usernameNotFoundErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

    usernameField2.setText("Username");
    usernameField2.setPreferredSize(new java.awt.Dimension(200, 30));
    usernameField2.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        usernameField2FocusGained(evt);
      }
    });
    jSignUpLogin.add(usernameField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

    passwordField2.setText("Password");
    passwordField2.setPreferredSize(new java.awt.Dimension(200, 30));
    passwordField2.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        passwordField2FocusGained(evt);
      }
    });
    jSignUpLogin.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

    loginLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
    loginLabel.setForeground(new java.awt.Color(204, 204, 204));
    loginLabel.setText("Login");
    jSignUpLogin.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

    smallbackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground_small.jpg"))); // NOI18N
    smallbackgroundImageLabel.setToolTipText("");
    jSignUpLogin.add(smallbackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
    right_panel.setLayout(right_panelLayout);
    right_panelLayout.setHorizontalGroup(
      right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 290, Short.MAX_VALUE)
    );
    right_panelLayout.setVerticalGroup(
      right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 510, Short.MAX_VALUE)
    );

    jSignUpLogin.add(right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 290, 510));

    jInvalidUsername.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
    jInvalidUsername.setPreferredSize(new java.awt.Dimension(678, 511));
    jInvalidUsername.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    smallbackgroundImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground_small.jpg"))); // NOI18N
    smallbackgroundImageLabel1.setToolTipText("Check username availablitiy");
    jInvalidUsername.add(smallbackgroundImageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jInvalidUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 15, Short.MAX_VALUE)
          .addComponent(jInvalidUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 16, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
        
        if(validate.checkFirstName(firstNameField.getText())){
            firstNameField.setBackground(correct);
        }
        else
        firstNameField.setBackground(wrong);
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkLastName(lastNameField.getText())){
            lastNameField.setBackground(correct);
        }
        else
        lastNameField.setBackground(wrong);
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkEmail(emailField.getText())){
            emailErrorLabel.setVisible(false);
            emailField.setBackground(correct);
        }
        else {
            emailErrorLabel.setVisible(true);
            emailField.setBackground(wrong);
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkPasswd(passwordField.getText())){
            passwordErrorLabel.setVisible(false);
            passwordField.setBackground(correct);
        }
        else {
            passwordErrorLabel.setVisible(true);
            passwordField.setBackground(wrong);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        // TODO add your handling code here:
        if(validate.checkUsrnm(usernameField.getText())){
            usernameErrorLabel.setVisible(false);
            usernameField.setBackground(correct);
        }
        else {
            usernameErrorLabel.setVisible(true);
            usernameField.setBackground(wrong);
        }
    }//GEN-LAST:event_usernameFieldFocusLost

    private void signInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseClicked
        // TODO add your handling code here:
      results = 
         playerQueries.getPlayerByUsername(usernameField2.getText());
      System.out.println(results.size());
      System.out.println(results.get(0).getPassword());
      if(results.get(0).getPassword().equals(usernameField2.getText())){
        game.startAILoad();
        game.startPlayerLoad();
        game.startNameLoad();
        game.startUpdateTable(); 
        game.setVisible(true);
        dispose();
      }
      else
        usernameNotFoundErrorLabel.setVisible(true);
    }//GEN-LAST:event_signInButtonMouseClicked

    private void registerButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerButtonFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_registerButtonFocusLost

    private void registerButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseMoved
        // TODO add your handling code here:
        
        //if all the textfields are validated, user can click register button
        if(validate.checkFirstName(firstNameField.getText()) && 
                validate.checkLastName(lastNameField.getText()) &&
                validate.checkUsrnm(usernameField.getText()) &&
                validate.checkEmail(emailField.getText()) &&
                validate.checkPasswd(passwordField.getText())) {
            registerButton.setEnabled(true);
        } else {
            registerButton.setEnabled(false);
        }
    }//GEN-LAST:event_registerButtonMouseMoved

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        if(registerButton.isEnabled()){
            
            playerQueries.addPlayer(firstNameField.getText(), 
            lastNameField.getText(), emailField.getText(),
            usernameField.getText(), passwordField.getText());
            
            //makes a new game
            game.reset();
            game.setVisible(true);
            //sets players name as username
            game.setPlayersName(usernameField.getText());
            //closes the jframe
            dispose();
        }
    }//GEN-LAST:event_registerButtonMouseClicked

    private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
      // TODO add your handling code here:
      //true = unique
      //only create one object
      invalidUsername.setVisible(true);
        if(!checkUsername(usernameField.getText())){
          checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/exclamation_point_100x100.png"))); // NOI18N
          checkMessageLabel.setText("Username is unavailable");
        }
      else{
          checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/check_mark_100x100.png")));
          checkMessageLabel.setText("Username is available");
      }
    }//GEN-LAST:event_checkButtonMouseClicked

  private void doneButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButton2MouseClicked
    // TODO add your handling code here:

    invalidUsername.setVisible(false);
    //jSignUpLogin.setVisible(true);
  }//GEN-LAST:event_doneButton2MouseClicked

  private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
    // TODO add your handling code here:
    emailField.selectAll();
  }//GEN-LAST:event_emailFieldFocusGained

  private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
    // TODO add your handling code here:
    usernameField.selectAll();
  }//GEN-LAST:event_usernameFieldFocusGained

  private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
    // TODO add your handling code here:
    passwordField.selectAll();
  }//GEN-LAST:event_passwordFieldFocusGained

  private void usernameField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameField2FocusGained
    // TODO add your handling code here:
    usernameField2.selectAll();
  }//GEN-LAST:event_usernameField2FocusGained

  private void passwordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField2FocusGained
    // TODO add your handling code here:
    passwordField2.selectAll();
  }//GEN-LAST:event_passwordField2FocusGained

    public void setBattleshipFrame(JFrame_Battleship bs){
        game = bs;
    }
    

    //If true: username is unique, if false: username is already taken
    private boolean checkUsername(String username){
        results = 
         playerQueries.getPlayerByUsername(username);
        numberOfEntries = results.size();
        
        if (numberOfEntries == 0){
          System.out.println("true");
            return true;
        } else{
          System.out.println("false");
            return false;
        }
        
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton checkButton;
  private javax.swing.JLabel checkMarkIconLabel;
  private javax.swing.JLabel checkMessageLabel;
  private javax.swing.JButton doneButton2;
  private javax.swing.JLabel emailErrorLabel;
  private javax.swing.JTextField emailField;
  private javax.swing.JTextField firstNameField;
  private javax.swing.JInternalFrame invalidUsername;
  private javax.swing.JLayeredPane jInvalidUsername;
  private javax.swing.JPanel jSignUpLogin;
  private javax.swing.JTextField lastNameField;
  private javax.swing.JPanel left_panel;
  private javax.swing.JLabel loginLabel;
  private javax.swing.JLabel passwordErrorLabel;
  private javax.swing.JTextField passwordField;
  private javax.swing.JTextField passwordField2;
  private javax.swing.JButton registerButton;
  private javax.swing.JPanel right_panel;
  private javax.swing.JButton signInButton;
  private javax.swing.JLabel signUpLabel;
  private javax.swing.JLabel smallbackgroundImageLabel;
  private javax.swing.JLabel smallbackgroundImageLabel1;
  private javax.swing.JLabel usernameErrorLabel;
  private javax.swing.JTextField usernameField;
  private javax.swing.JTextField usernameField2;
  private javax.swing.JLabel usernameNotFoundErrorLabel;
  // End of variables declaration//GEN-END:variables
}
