/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship_gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.List;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Brian
 */
public class JFrame_Battleship extends javax.swing.JFrame {
    private static final int a = 10; //size of board a x a
    private JButton[][] buttons_Player;
    private JButton[][] buttons_AI;
    private JLabel[] row_1;
    private JLabel[] row_2;
    private Background bg = new Background();
    int count=0;
    boolean ppre=true;
    Validate validation = new Validate();
    TextInputs menu;
    Color greyish = new Color(204,204,204);
    Font font0 = new Font("Rockwell", Font.PLAIN, 20);
    RegExCheck validate = new RegExCheck();
    PlayerInfoQueries playerQueries = new PlayerInfoQueries();
    private List<PlayerInfo> results;
    private int numberOfEntries = 0;
    Color correct = new Color(102,255,102);
    Color wrong = new Color(255,102,102);
    String name;
    /**
     * Creates new form IntroMenu
     */
    
    public JFrame_Battleship() {
        initComponents();
        Playerprepare();
        colSet();
        setLocationRelativeTo(null);  
        Tip.setForeground(greyish);
        Tip.setFont(font0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Login = new javax.swing.JLayeredPane();
    jSignUpLogin = new javax.swing.JPanel();
    invalidUsername = new javax.swing.JInternalFrame();
    checkMarkIconLabel = new javax.swing.JLabel();
    checkMessageLabel = new javax.swing.JLabel();
    doneButton2 = new javax.swing.JButton();
    left_panel = new javax.swing.JPanel();
    registerButton = new javax.swing.JButton();
    lastNameField = new javax.swing.JTextField();
    emailErrorLabel = new javax.swing.JLabel();
    signUpLabel = new javax.swing.JLabel();
    passwordErrorLabel = new javax.swing.JLabel();
    usernameErrorLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JTextField();
    emailField = new javax.swing.JTextField();
    usernameField = new javax.swing.JTextField();
    checkButton = new javax.swing.JButton();
    firstNameField = new javax.swing.JTextField();
    jCheckBox1 = new javax.swing.JCheckBox();
    jCheckBox2 = new javax.swing.JCheckBox();
    signInButton = new javax.swing.JButton();
    usernameNotFoundErrorLabel = new javax.swing.JLabel();
    usernameField2 = new javax.swing.JTextField();
    passwordField2 = new javax.swing.JTextField();
    loginLabel = new javax.swing.JLabel();
    right_panel = new javax.swing.JPanel();
    smallbackgroundImageLabel = new javax.swing.JLabel();
    jIntroMenuPane = new javax.swing.JLayeredPane();
    startButton = new javax.swing.JButton();
    rulesButton = new javax.swing.JButton();
    battleshipLogo = new javax.swing.JLabel();
    backgroundImageLabel = new javax.swing.JLabel();
    jRulesPane = new javax.swing.JLayeredPane();
    rulesTitle = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();
    rulesText = new javax.swing.JTextArea();
    backgroundImageLabel1 = new javax.swing.JLabel();
    jGamePlayPane = new javax.swing.JLayeredPane();
    Invalid_Intern_Frame = new javax.swing.JInternalFrame("Invalid Input");
    jButton1 = new javax.swing.JButton();
    Invalid_Label = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    fireButton = new javax.swing.JButton();
    playerNameLabel = new javax.swing.JLabel();
    jBoardPane_Player = new javax.swing.JLayeredPane();
    jBoardPane_AI = new javax.swing.JLayeredPane();
    AI_Label = new javax.swing.JLabel();
    col_2 = new javax.swing.JLabel();
    Tip = new javax.swing.JLabel();
    col_1 = new javax.swing.JLabel();
    WinLose = new javax.swing.JLabel();
    backgroundImageLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Login.setOpaque(true);
    Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSignUpLogin.setMinimumSize(new java.awt.Dimension(640, 461));
    jSignUpLogin.setOpaque(false);
    jSignUpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    invalidUsername.setTitle("Username Availability");
    invalidUsername.setFrameIcon(null);
    invalidUsername.setVisible(false);

    checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/exclamation_point_100x100.png"))); // NOI18N

    checkMessageLabel.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
    checkMessageLabel.setText("Username is unavailable");

    doneButton2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
    doneButton2.setText("done");
    doneButton2.setFocusable(false);
    doneButton2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        doneButton2MouseClicked(evt);
      }
    });

    javax.swing.GroupLayout invalidUsernameLayout = new javax.swing.GroupLayout(invalidUsername.getContentPane());
    invalidUsername.getContentPane().setLayout(invalidUsernameLayout);
    invalidUsernameLayout.setHorizontalGroup(
      invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(invalidUsernameLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(checkMarkIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(checkMessageLabel))
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(doneButton2)))
        .addContainerGap(61, Short.MAX_VALUE))
    );
    invalidUsernameLayout.setVerticalGroup(
      invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(invalidUsernameLayout.createSequentialGroup()
        .addGroup(invalidUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(invalidUsernameLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(checkMarkIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, invalidUsernameLayout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(checkMessageLabel)
            .addGap(18, 18, 18)
            .addComponent(doneButton2)))
        .addContainerGap(42, Short.MAX_VALUE))
    );

    jSignUpLogin.add(invalidUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 480, 200));

    left_panel.setOpaque(false);
    left_panel.setPreferredSize(new java.awt.Dimension(339, 511));

    registerButton.setBackground(new java.awt.Color(102, 102, 102));
    registerButton.setForeground(new java.awt.Color(204, 204, 204));
    registerButton.setText("Register");
    registerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
    registerButton.setPreferredSize(new java.awt.Dimension(80, 40));
    registerButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseMoved(java.awt.event.MouseEvent evt) {
        registerButtonMouseMoved(evt);
      }
    });
    registerButton.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        registerButtonFocusLost(evt);
      }
    });
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        registerButtonMouseClicked(evt);
      }
    });

    lastNameField.setText("Last name");
    lastNameField.setPreferredSize(new java.awt.Dimension(200, 30));
    lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        lastNameFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        lastNameFieldFocusLost(evt);
      }
    });

    emailErrorLabel.setVisible(false);
    emailErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    emailErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    emailErrorLabel.setText("Please enter valid email address\n");

    signUpLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
    signUpLabel.setForeground(new java.awt.Color(204, 204, 204));
    signUpLabel.setText("Sign Up");

    passwordErrorLabel.setVisible(false);
    passwordErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    passwordErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    passwordErrorLabel.setText("At least1 uppercase, 1 lowercase, 1 numeric, 8 - 15 chars.");

    usernameErrorLabel.setVisible(false);
    usernameErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    usernameErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    usernameErrorLabel.setText("Must contain 1 lowercase, 4 - 10 chars");
    usernameErrorLabel.setToolTipText("");

    passwordField.setText("Password");
    passwordField.setPreferredSize(new java.awt.Dimension(200, 30));
    passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        passwordFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        passwordFieldFocusLost(evt);
      }
    });
    passwordField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        passwordFieldActionPerformed(evt);
      }
    });

    emailField.setText("Email address");
    emailField.setPreferredSize(new java.awt.Dimension(200, 30));
    emailField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        emailFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        emailFieldFocusLost(evt);
      }
    });

    usernameField.setText("Username");
    usernameField.setPreferredSize(new java.awt.Dimension(200, 30));
    usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        usernameFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        usernameFieldFocusLost(evt);
      }
    });

    checkButton.setBackground(new java.awt.Color(102, 102, 102));
    checkButton.setForeground(new java.awt.Color(204, 204, 204));
    checkButton.setText("check");
    checkButton.setToolTipText("Check availablility");
    checkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    checkButton.setPreferredSize(new java.awt.Dimension(80, 40));
    checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        checkButtonMouseClicked(evt);
      }
    });

    firstNameField.setText("First name");
    firstNameField.setPreferredSize(new java.awt.Dimension(200, 30));
    firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        firstNameFieldFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        firstNameFieldFocusLost(evt);
      }
    });

    jCheckBox1.setForeground(new java.awt.Color(240, 240, 240));
    jCheckBox1.setText("Male");
    jCheckBox1.setOpaque(false);
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox1ActionPerformed(evt);
      }
    });

    jCheckBox2.setForeground(new java.awt.Color(240, 240, 240));
    jCheckBox2.setText("Female");
    jCheckBox2.setOpaque(false);

    javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
    left_panel.setLayout(left_panelLayout);
    left_panelLayout.setHorizontalGroup(
      left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
        .addContainerGap(298, Short.MAX_VALUE)
        .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jCheckBox2)
          .addComponent(jCheckBox1))
        .addGap(43, 43, 43))
      .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(left_panelLayout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(60, 60, 60)
              .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(48, 48, 48)
              .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(48, 48, 48)
              .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(emailErrorLabel))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(usernameErrorLabel))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(0, 0, 0)
              .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(passwordErrorLabel)
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(50, 50, 50)
              .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(left_panelLayout.createSequentialGroup()
              .addGap(100, 100, 100)
              .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    left_panelLayout.setVerticalGroup(
      left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
        .addContainerGap(369, Short.MAX_VALUE)
        .addComponent(jCheckBox1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jCheckBox2)
        .addGap(92, 92, 92))
      .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(left_panelLayout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(25, 25, 25)
          .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(18, 18, 18)
          .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(7, 7, 7)
          .addComponent(emailErrorLabel)
          .addGap(4, 4, 4)
          .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(10, 10, 10)
          .addComponent(usernameErrorLabel)
          .addGap(4, 4, 4)
          .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(10, 10, 10)
          .addComponent(passwordErrorLabel)
          .addGap(4, 4, 4)
          .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(10, 10, 10)
          .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );

    jSignUpLogin.add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 400, 510));
    left_panel.setVisible(true);

    signInButton.setBackground(new java.awt.Color(102, 102, 102));
    signInButton.setForeground(new java.awt.Color(204, 204, 204));
    signInButton.setText("Sign in");
    signInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    signInButton.setPreferredSize(new java.awt.Dimension(70, 40));
    signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        signInButtonMouseClicked(evt);
      }
    });
    jSignUpLogin.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, -1));

    usernameNotFoundErrorLabel.setVisible(false);
    usernameNotFoundErrorLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
    usernameNotFoundErrorLabel.setForeground(new java.awt.Color(255, 102, 102));
    usernameNotFoundErrorLabel.setText("Username not found! Please sign up.");
    jSignUpLogin.add(usernameNotFoundErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

    usernameField2.setText("Username");
    usernameField2.setPreferredSize(new java.awt.Dimension(200, 30));
    usernameField2.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        usernameField2FocusGained(evt);
      }
    });
    jSignUpLogin.add(usernameField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

    passwordField2.setText("Password");
    passwordField2.setPreferredSize(new java.awt.Dimension(200, 30));
    passwordField2.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        passwordField2FocusGained(evt);
      }
    });
    jSignUpLogin.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

    loginLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
    loginLabel.setForeground(new java.awt.Color(204, 204, 204));
    loginLabel.setText("Login");
    jSignUpLogin.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

    right_panel.setOpaque(false);

    javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
    right_panel.setLayout(right_panelLayout);
    right_panelLayout.setHorizontalGroup(
      right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 290, Short.MAX_VALUE)
    );
    right_panelLayout.setVerticalGroup(
      right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 510, Short.MAX_VALUE)
    );

    jSignUpLogin.add(right_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 290, 510));

    Login.add(jSignUpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 660, 470));

    smallbackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground_small.jpg"))); // NOI18N
    Login.add(smallbackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 860, 640));

    Login.setOpaque(false);

    getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));
    Login.setVisible(false);

    jIntroMenuPane.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
    jIntroMenuPane.setMaximumSize(new java.awt.Dimension(1080, 800));
    jIntroMenuPane.setName(""); // NOI18N
    jIntroMenuPane.setPreferredSize(new java.awt.Dimension(1080, 800));
    jIntroMenuPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    startButton.setBackground(new java.awt.Color(102, 102, 102));
    startButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
    startButton.setForeground(new java.awt.Color(204, 204, 204));
    startButton.setText("Start");
    startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    startButton.setMaximumSize(new java.awt.Dimension(140, 60));
    startButton.setMinimumSize(new java.awt.Dimension(140, 60));
    startButton.setPreferredSize(new java.awt.Dimension(140, 60));
    startButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        startButtonMouseClicked(evt);
      }
    });
    jIntroMenuPane.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

    rulesButton.setBackground(new java.awt.Color(102, 102, 102));
    rulesButton.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
    rulesButton.setForeground(new java.awt.Color(204, 204, 204));
    rulesButton.setText("Rules");
    rulesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    rulesButton.setMaximumSize(new java.awt.Dimension(140, 60));
    rulesButton.setMinimumSize(new java.awt.Dimension(140, 60));
    rulesButton.setPreferredSize(new java.awt.Dimension(140, 60));
    rulesButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        rulesButtonMouseClicked(evt);
      }
    });
    jIntroMenuPane.add(rulesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

    battleshipLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/battleship-movie-logo.png"))); // NOI18N
    jIntroMenuPane.add(battleshipLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

    backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground.jpg"))); // NOI18N
    backgroundImageLabel.setAlignmentY(0.0F);
    backgroundImageLabel.setOpaque(true);
    backgroundImageLabel.setVerifyInputWhenFocusTarget(false);
    jIntroMenuPane.add(backgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    getContentPane().add(jIntroMenuPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1095, -1));

    jRulesPane.setVisible(false);
    jRulesPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
    jRulesPane.setMaximumSize(new java.awt.Dimension(1024, 1000));
    jRulesPane.setPreferredSize(new java.awt.Dimension(1080, 800));
    jRulesPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    rulesTitle.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
    rulesTitle.setForeground(new java.awt.Color(204, 204, 204));
    rulesTitle.setText("Rules for BattleShip");
    jRulesPane.add(rulesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

    closeButton.setText("close");
    closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        closeButtonMouseClicked(evt);
      }
    });
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });
    jRulesPane.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 750, -1, -1));

    rulesText.setEditable(false);
    rulesText.setBackground(new java.awt.Color(102, 102, 102));
    rulesText.setColumns(20);
    rulesText.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
    rulesText.setForeground(new java.awt.Color(204, 204, 204));
    rulesText.setRows(5);
    rulesText.setText("User chooses a spot on the grid to strike in the text field.\n\nIf the user guesses right, the area will turn red to mark as a\"hit\". \nIf the user guesses wrong, the area will turn yellow as a\"miss\".");
    rulesText.setDisabledTextColor(new java.awt.Color(153, 153, 153));
    jRulesPane.add(rulesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 780, -1));

    backgroundImageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground.jpg"))); // NOI18N
    jRulesPane.add(backgroundImageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    getContentPane().add(jRulesPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1095, 820));

    jGamePlayPane.setVisible(false);
    jGamePlayPane.setMaximumSize(new java.awt.Dimension(1024, 1000));
    jGamePlayPane.setName(""); // NOI18N
    jGamePlayPane.setPreferredSize(new java.awt.Dimension(1080, 800));
    jGamePlayPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Invalid_Intern_Frame.setVisible(true);

    jButton1.setText("Close");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton1MouseClicked(evt);
      }
    });

    Invalid_Label.setText("Invalid Notice");

    javax.swing.GroupLayout Invalid_Intern_FrameLayout = new javax.swing.GroupLayout(Invalid_Intern_Frame.getContentPane());
    Invalid_Intern_Frame.getContentPane().setLayout(Invalid_Intern_FrameLayout);
    Invalid_Intern_FrameLayout.setHorizontalGroup(
      Invalid_Intern_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Invalid_Intern_FrameLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1))
      .addComponent(Invalid_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    Invalid_Intern_FrameLayout.setVerticalGroup(
      Invalid_Intern_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Invalid_Intern_FrameLayout.createSequentialGroup()
        .addComponent(Invalid_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1))
    );

    jGamePlayPane.add(Invalid_Intern_Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 210, 150));
    Invalid_Intern_Frame.setVisible(false);
    Invalid_Intern_Frame.setResizable(false);

    jTextField1.setText("Input Format A1A5");
    jTextField1.setToolTipText("");
    jTextField1.setMinimumSize(new java.awt.Dimension(98, 20));
    jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTextField1MouseClicked(evt);
      }
    });
    jGamePlayPane.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 638, 140, -1));

    fireButton.setBackground(new java.awt.Color(102, 102, 102));
    fireButton.setForeground(new java.awt.Color(204, 204, 204));
    fireButton.setText("Place");
    fireButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.white));
    fireButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fireButtonActionPerformed(evt);
      }
    });
    jGamePlayPane.add(fireButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, 50, 30));

    playerNameLabel.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
    playerNameLabel.setForeground(new java.awt.Color(204, 204, 204));
    playerNameLabel.setText("Player's Name");
    jGamePlayPane.add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 350, 40));

    jBoardPane_Player.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBoardPane_Player.setPreferredSize(new java.awt.Dimension(500, 500));

    javax.swing.GroupLayout jBoardPane_PlayerLayout = new javax.swing.GroupLayout(jBoardPane_Player);
    jBoardPane_Player.setLayout(jBoardPane_PlayerLayout);
    jBoardPane_PlayerLayout.setHorizontalGroup(
      jBoardPane_PlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 496, Short.MAX_VALUE)
    );
    jBoardPane_PlayerLayout.setVerticalGroup(
      jBoardPane_PlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 496, Short.MAX_VALUE)
    );

    ButtonTablePlayer();

    jGamePlayPane.add(jBoardPane_Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

    jBoardPane_AI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jBoardPane_AI.setPreferredSize(new java.awt.Dimension(500, 500));

    javax.swing.GroupLayout jBoardPane_AILayout = new javax.swing.GroupLayout(jBoardPane_AI);
    jBoardPane_AI.setLayout(jBoardPane_AILayout);
    jBoardPane_AILayout.setHorizontalGroup(
      jBoardPane_AILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 496, Short.MAX_VALUE)
    );
    jBoardPane_AILayout.setVerticalGroup(
      jBoardPane_AILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 496, Short.MAX_VALUE)
    );

    ButtonTableAI();
    AIprepare();

    jGamePlayPane.add(jBoardPane_AI, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

    AI_Label.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
    AI_Label.setForeground(new java.awt.Color(204, 204, 204));
    AI_Label.setText("AI");
    jGamePlayPane.add(AI_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

    col_2.setForeground(new java.awt.Color(204, 204, 204));
    col_2.setText("         0              1              2              3              4              5              6             7              8              9");
    jGamePlayPane.add(col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 500, 30));

    Tip.setText("Please enter the coordinates to place "+bg.unit[count]+" ship\nformat is B-A5");
    Tip.setForeground(new java.awt.Color(204, 204, 204));
    jGamePlayPane.add(Tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

    col_1.setForeground(new java.awt.Color(204, 204, 204));
    col_1.setText("         0              1              2              3              4              5              6             7              8              9");
    jGamePlayPane.add(col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 510, 30));

    WinLose.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
    WinLose.setForeground(new java.awt.Color(204, 204, 204));
    WinLose.setOpaque(true);
    jGamePlayPane.add(WinLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 240, 100));
    WinLose.setBackground(Color.green);
    WinLose.setVisible(false);

    backgroundImageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/BSBackground.jpg"))); // NOI18N
    jGamePlayPane.add(backgroundImageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    getContentPane().add(jGamePlayPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1095, 820));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
      jIntroMenuPane.setVisible(true);
      jRulesPane.setVisible(false);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void rulesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rulesButtonMouseClicked
        // TODO add your handling code here:
      jIntroMenuPane.setVisible(false);
      jRulesPane.setVisible(true);
    }//GEN-LAST:event_rulesButtonMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
      
//      menu = new TextInputs();
//      this.setVisible(false);
//      menu.setBattleshipFrame(this);
      jIntroMenuPane.setVisible(false);
      this.setSize(new Dimension(700, 550));
      Login.setVisible(true);
      
    }//GEN-LAST:event_startButtonMouseClicked

  private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
    boolean valid;
    String temp = jTextField1.getText();
    System.out.println(temp);
    //place ship
    if(ppre){
      if(validation.place(temp)){
        valid=bg.place(temp, count);
        if(valid && validation.place(temp)){   //if true = valid input update gui table
          count++;
          if(count<5){
            Playerprepare();  //update prompt label
          }//placing ship ends
          else{
            PlayerSave();
            AISave();
            NameSave();
            //update label text
            Tip.setText("Ready to fire!");
            //update button text
            fireButton.setText("Fire");
            //set ai buttons enable
            enableAI(true);
            ppre=false;
          }
          UpdateTable();
        }
        else{
          //add new label
          System.out.println("Invalid input");
          Invalid_Intern_Frame.setVisible(true);
          Invalid_Label.setText("Invalid_Input: Overlap/Unit");
        }
      }
      else{
        //add new label
        System.out.println("Invalid input");
        Invalid_Intern_Frame.setVisible(true);
        Invalid_Label.setText("Invalid_Input: place format A1A5");
      }
        
    }
    //fire
    else{
      //validation needed length=2
      if(validation.fire(temp)){
        if(bg.pFireCheck(temp)){
          //update table (only that index) AND COLOR
          buttons_AI[bg.y1][bg.x1].setText(String.valueOf(bg.real[bg.y1][bg.x1]));
          if(bg.real[bg.y1][bg.x1]=='X')
            buttons_AI[bg.y1][bg.x1].setBackground(Color.red);
          else
            buttons_AI[bg.y1][bg.x1].setBackground(Color.yellow);
          //disable fire button
          fireButton.setEnabled(false);
          if(bg.chkWin(bg.real)){
            //update Label
            WinLose.setText(playerNameLabel.getText()+" wins");
            WinLose.setVisible(true);
            System.out.println("Player wins");
            reset();
          }
          //player wins = false
          //game continue
          else{
            //ai buttons disable
            enableAI(false);
            /**ai fire turn begins
             * update player table
             * ai fire turn ends
            */
            AIFire();
            //ai wins
            if(bg.chkWin(bg.player)){
              //update label
              WinLose.setText(playerNameLabel.getText()+" loses");
              WinLose.setVisible(true);
              System.out.println("Player loses");
              reset();
            }
            else{
              //set fire button, ai buttons enable
              enableAI(true);
              fireButton.setEnabled(true);
              //save
              AISave();
              PlayerSave();
            }
          }//ai wins = false (game continue
        }
        else{
          //add one new label
          System.out.println("Fire Invalid");
          Invalid_Intern_Frame.setVisible(true);
          Invalid_Label.setText("Invalid Input: Overlap");
        }
      }
      else{
        //add one new label
        System.out.println("Fire Invalid");
        Invalid_Intern_Frame.setVisible(true);
        Invalid_Label.setText("Invalid Input: Fire Format A1");
      }
    }
  }//GEN-LAST:event_fireButtonActionPerformed

  private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
    // TODO add your handling code here:
    jTextField1.selectAll();
  }//GEN-LAST:event_jTextField1MouseClicked

  private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    // TODO add your handling code here:
    Invalid_Intern_Frame.setVisible(false);
  }//GEN-LAST:event_jButton1MouseClicked

  private void doneButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButton2MouseClicked
    // TODO add your handling code here:

    invalidUsername.setVisible(false);
    //jSignUpLogin.setVisible(true);
  }//GEN-LAST:event_doneButton2MouseClicked

  private void registerButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseMoved
    // TODO add your handling code here:

    //if all the textfields are validated, user can click register button
    if(validate.checkFirstName(firstNameField.getText()) &&
      validate.checkLastName(lastNameField.getText()) &&
      validate.checkUsrnm(usernameField.getText()) &&
      validate.checkEmail(emailField.getText()) &&
      validate.checkPasswd(passwordField.getText())) {
      registerButton.setEnabled(true);
    } else {
      registerButton.setEnabled(false);
    }
  }//GEN-LAST:event_registerButtonMouseMoved

  private void registerButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerButtonFocusLost
    // TODO add your handling code here:
  }//GEN-LAST:event_registerButtonFocusLost

  private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
    // TODO add your handling code here:
    if(registerButton.isEnabled()){

      playerQueries.addPlayer(firstNameField.getText(),
        lastNameField.getText(), emailField.getText(),
        usernameField.getText(), passwordField.getText());
      name=usernameField.getText();
      //makes a new game
      //reset();
      this.setSize(new Dimension(1095, 820));
      //setVisible(true);
      //sets players name as username
      setPlayersName(usernameField.getText());
      jGamePlayPane.setVisible(true);
      Login.setVisible(false);
    }
  }//GEN-LAST:event_registerButtonMouseClicked

  private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
    // TODO add your handling code here:
    lastNameField.selectAll();
  }//GEN-LAST:event_lastNameFieldFocusGained

  private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
    // TODO add your handling code here:
    if(validate.checkLastName(lastNameField.getText())){
      lastNameField.setBackground(correct);
    }
    else
    lastNameField.setBackground(wrong);
  }//GEN-LAST:event_lastNameFieldFocusLost

  private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
    // TODO add your handling code here:
    passwordField.selectAll();
  }//GEN-LAST:event_passwordFieldFocusGained

  private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
    // TODO add your handling code here:
    if(validate.checkPasswd(passwordField.getText())){
      passwordErrorLabel.setVisible(false);
      passwordField.setBackground(correct);
    }
    else {
      passwordErrorLabel.setVisible(true);
      passwordField.setBackground(wrong);
    }
  }//GEN-LAST:event_passwordFieldFocusLost

  private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_passwordFieldActionPerformed

  private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
    // TODO add your handling code here:
    emailField.selectAll();
  }//GEN-LAST:event_emailFieldFocusGained

  private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
    // TODO add your handling code here:
    if(validate.checkEmail(emailField.getText())){
      emailErrorLabel.setVisible(false);
      emailField.setBackground(correct);
    }
    else {
      emailErrorLabel.setVisible(true);
      emailField.setBackground(wrong);
    }
  }//GEN-LAST:event_emailFieldFocusLost

  private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
    // TODO add your handling code here:
    usernameField.selectAll();
  }//GEN-LAST:event_usernameFieldFocusGained

  private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
    // TODO add your handling code here:
    if(validate.checkUsrnm(usernameField.getText())){
      usernameErrorLabel.setVisible(false);
      usernameField.setBackground(correct);
    }
    else {
      usernameErrorLabel.setVisible(true);
      usernameField.setBackground(wrong);
    }
  }//GEN-LAST:event_usernameFieldFocusLost

  private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
    // TODO add your handling code here:
    //true = unique
    //only create one object
    System.out.println("check button clicked");
    //invalidUsername.setVisible(true);
    if(!checkUsername(usernameField.getText())){
      System.out.println("username invalid");
      checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/exclamation_point_100x100.png"))); // NOI18N
      checkMessageLabel.setText("Username is unavailable");
    }
    else{
      System.out.println("change text and label");
      checkMarkIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/battleship_gui/check_mark_100x100.png"))); // NOI18N
      checkMessageLabel.setText("Username is available");
    }
    //invalidUsername.repaint();
    invalidUsername.setVisible(true);
  }//GEN-LAST:event_checkButtonMouseClicked

  private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
    // TODO add your handling code here:
    firstNameField.selectAll();
  }//GEN-LAST:event_firstNameFieldFocusGained

  private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
    // TODO add your handling code here:

    if(validate.checkFirstName(firstNameField.getText())){
      firstNameField.setBackground(correct);
    }
    else
    firstNameField.setBackground(wrong);
  }//GEN-LAST:event_firstNameFieldFocusLost

  private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jCheckBox1ActionPerformed

  private void signInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseClicked
    // TODO add your handling code here:
    System.out.println("signInButtonMouseClicked");
    
    System.out.println(usernameField2.getText());
    results =
    playerQueries.getPlayerByUsername(usernameField2.getText());

    System.out.println("result size = "+results.size());

    if(results.size()>0){
      System.out.println("results not null");
      System.out.println(results.get(0).getPassword());
      //match password
      if(results.get(0).getPassword().equals(passwordField2.getText())){
        //change size
        this.setSize(new Dimension(1095, 820));
        Login.setVisible(false);
        jGamePlayPane.setVisible(true);
        System.out.println("Record load");
        name=results.get(0).getUsername();
        AILoad();
        System.out.println("Result Load");
        PlayerLoad();
        System.out.println("result load ");
        NameLoad();
        setVisible(true);
      }
    }
    else
    usernameNotFoundErrorLabel.setVisible(true);
  }//GEN-LAST:event_signInButtonMouseClicked

  private void usernameField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameField2FocusGained
    // TODO add your handling code here:
    usernameField2.selectAll();
  }//GEN-LAST:event_usernameField2FocusGained

  private void passwordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField2FocusGained
    // TODO add your handling code here:
    passwordField2.selectAll();
  }//GEN-LAST:event_passwordField2FocusGained

  
    //creates the button table for the player
    public void ButtonTablePlayer() {
      //adds grid to place 2D array
      jBoardPane_Player.setLayout(new GridLayout(a,a));
      //declare size of button 2D array
      buttons_Player = new JButton[a][a];
      for(int i=0;i<a;i++){
        for(int j=0;j<a;j++){
          //create new JButton
          buttons_Player[i][j] = new JButton();
//          buttons_Player[i][j].setText(Integer.toString(i)+" "+Integer.toString(j));
          buttons_Player[i][j].setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
          buttons_Player[i][j].setBackground(Color.white);
          buttons_Player[i][j].setEnabled(false);
          //addes buttons to the layered pane
          jBoardPane_Player.add(buttons_Player[i][j]);
        }
      }
    }
     
    //creates the button table for the AI
    public void ButtonTableAI() {
      ActionListener aiclk = new ButtonListenerAI();
      jBoardPane_AI.setLayout(new GridLayout(a,a));
      //declare size of button array
      buttons_AI = new JButton[a][a];
      for(int i=0;i<a;i++){
        for(int j=0;j<a;j++){
          //create new object
          buttons_AI[i][j] = new JButton();
//          buttons_AI[i][j].setText(Integer.toString(i)+" "+Integer.toString(j));
          buttons_AI[i][j].setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
          buttons_AI[i][j].addActionListener(aiclk);
          buttons_AI[i][j].setBackground(Color.white);
          buttons_AI[i][j].setEnabled(false); //disable before prepare
          //adds buttons to the layered pane
          jBoardPane_AI.add(buttons_AI[i][j]);
        }
      }
    }
    

    //PLAYER FIRE 
    //create an action listener class for AI
    public class ButtonListenerAI implements ActionListener {  
      @Override
      public void actionPerformed(ActionEvent e){
        for (int i = 0; i < a; i++){
          for (int j = 0; j < a; j++){
            if(e.getSource()==buttons_AI[i][j]){ //gameButtons[i][j] was clicked
              //Your code here
              System.out.println("AI"+i+" "+j);
              if(bg.pFireCheck(i, j)){
                //update table (only that index) AND COLOR
                
                buttons_AI[bg.y1][bg.x1].setText(String.valueOf(bg.real[bg.y1][bg.x1]));
                if(bg.real[bg.y1][bg.x1]=='X')
                  buttons_AI[bg.y1][bg.x1].setBackground(Color.red);
                else
                  buttons_AI[bg.y1][bg.x1].setBackground(Color.yellow);
                //set fire button, ai buttons disable
                fireButton.setEnabled(false);
                enableAI(false);
                if(bg.chkWin(bg.real)){
                  //update Label
                  WinLose.setText(playerNameLabel.getText()+" wins");
                  WinLose.setVisible(true);
                  System.out.println("Player wins");
                  reset();
                }
                else{
                  /**ai fire turn begins
                  * update player table
                  * ai fire turn ends
                  */
                  AIFire();
                  if(bg.chkWin(bg.player)){//ai wins
                    //update Label
                    WinLose.setText(playerNameLabel.getText()+" loses");
                    WinLose.setVisible(true);
                    System.out.println("Player loses");
                    reset();
                  }
                  else{
                    //set fire button, ai buttons enable
                    enableAI(true);
                    fireButton.setEnabled(true);
                    //save
                    PlayerSave();
                    AISave();
                  }
                }
              }
            }
          }
        }
      }
    }
    
    public void setPlayersName(String username){
        playerNameLabel.setText(username);
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel AI_Label;
  private javax.swing.JInternalFrame Invalid_Intern_Frame;
  private javax.swing.JLabel Invalid_Label;
  private javax.swing.JLayeredPane Login;
  private javax.swing.JLabel Tip;
  private javax.swing.JLabel WinLose;
  private javax.swing.JLabel backgroundImageLabel;
  private javax.swing.JLabel backgroundImageLabel1;
  private javax.swing.JLabel backgroundImageLabel2;
  private javax.swing.JLabel battleshipLogo;
  private javax.swing.JButton checkButton;
  private javax.swing.JLabel checkMarkIconLabel;
  private javax.swing.JLabel checkMessageLabel;
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel col_1;
  private javax.swing.JLabel col_2;
  private javax.swing.JButton doneButton2;
  private javax.swing.JLabel emailErrorLabel;
  private javax.swing.JTextField emailField;
  private javax.swing.JButton fireButton;
  private javax.swing.JTextField firstNameField;
  private javax.swing.JInternalFrame invalidUsername;
  private javax.swing.JLayeredPane jBoardPane_AI;
  private javax.swing.JLayeredPane jBoardPane_Player;
  private javax.swing.JButton jButton1;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JLayeredPane jGamePlayPane;
  private javax.swing.JLayeredPane jIntroMenuPane;
  private javax.swing.JLayeredPane jRulesPane;
  private javax.swing.JPanel jSignUpLogin;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField lastNameField;
  private javax.swing.JPanel left_panel;
  private javax.swing.JLabel loginLabel;
  private javax.swing.JLabel passwordErrorLabel;
  private javax.swing.JTextField passwordField;
  private javax.swing.JTextField passwordField2;
  private javax.swing.JLabel playerNameLabel;
  private javax.swing.JButton registerButton;
  private javax.swing.JPanel right_panel;
  private javax.swing.JButton rulesButton;
  private javax.swing.JTextArea rulesText;
  private javax.swing.JLabel rulesTitle;
  private javax.swing.JButton signInButton;
  private javax.swing.JLabel signUpLabel;
  private javax.swing.JLabel smallbackgroundImageLabel;
  private javax.swing.JButton startButton;
  private javax.swing.JLabel usernameErrorLabel;
  private javax.swing.JTextField usernameField;
  private javax.swing.JTextField usernameField2;
  private javax.swing.JLabel usernameNotFoundErrorLabel;
  // End of variables declaration//GEN-END:variables

  //[a-jA-J]{1}[0-9]{1}
  //[a-jA-J]{1}\-{1}[a-jA-J]{1}[0-9]{1}
  //a1-a5
  private void AIprepare(){
    bg.ai();
      for(int i=0;i<10;i++){
        for(int j=0;j<10;j++){
          if(bg.fake[i][j]!=' '){
            buttons_AI[i][j].setText(String.valueOf(bg.fake[i][j]));
            buttons_AI[i][j].setBackground(Color.gray);
          }
        }
      }
  }
  private void Playerprepare(){
     
    Tip.setText("Enter the coordinates to place "+bg.unit[count]+"-unit ship");
  }
  private void UpdateTable(){
    for(int i=0;i<bg.num;i++){
      for(int j=0;j<bg.num;j++){
        if(bg.player[i][j]!=' '){
          buttons_Player[i][j].setBackground(Color.gray);
          buttons_Player[i][j].setText(String.valueOf(bg.player[i][j]));
        }
      }
    }
  }
  
  private void enableAI(boolean bool){
    for(int i=0;i<a;i++){
      for(int j=0;j<a;j++){
        buttons_AI[i][j].setEnabled(bool);
      }
    }
  }
  private void AIFire(){
    bg.aiFirebg();
    buttons_Player[bg.aiProp.y][bg.aiProp.x].setText(String.valueOf(bg.player[bg.aiProp.y][bg.aiProp.x]));
    if(bg.player[bg.aiProp.y][bg.aiProp.x]=='X'){
      buttons_Player[bg.aiProp.y][bg.aiProp.x].setBackground(Color.red);
      System.out.println("hit"+bg.aiProp.y+" "+bg.aiProp.x);
    }
    else{
      buttons_Player[bg.aiProp.y][bg.aiProp.x].setBackground(Color.yellow);
      System.out.println("miss"+bg.aiProp.y+" "+bg.aiProp.x);
    }
    PlayerSave();
    AISave();
  }
  //set a-j, 0-9
  private void colSet(){
    row_1 = new JLabel[10];
    row_2 = new JLabel[10];
    for(int i=0;i<10;i++){
      row_1[i] = new JLabel(String.valueOf((char)(i+65)));
      row_2[i] = new JLabel(String.valueOf((char)(i+65)));
      jGamePlayPane.add(row_1[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(20, (120+i*50), -1, -1));
      jGamePlayPane.add(row_2[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(555, (120+i*50), -1, -1));
    }
  }
  //save ai table
  private void AISave(){
    try(BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(name.toString()+"AI.txt"), "UTF-8"))){
      for(int i=0;i<10;i++){
        for(int j=0;j<10;j++){
          writer.write(String.valueOf(bg.real[i][j]));
        }
        writer.write("\n");
      }
      writer.close();
    }catch (IOException ex){
      //handle me
      ex.printStackTrace();
    }
  }
  //load ai
  private void AILoad(){
     
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(name.toString()+"AI.txt"), "utf-8"))) {
      String temp;
      int counter=0;
      while((temp=reader.readLine())!=null){
        for(int j=0;j<10;j++){
         bg. real[counter][j]=temp.charAt(j);
         if(bg.real[counter][j]=='X'){
            buttons_AI[counter][j].setBackground(Color.red);
            buttons_AI[counter][j].setText(String.valueOf(bg.real[counter][j]));
          }
          else if(bg.real[counter][j]=='O'){
            buttons_AI[counter][j].setBackground(Color.yellow);
            buttons_AI[counter][j].setText(String.valueOf(bg.real[counter][j]));
          }
        }
        counter++;
        System.out.println(temp);
        System.out.println(temp.length());
      }
      reader.close();
      //set ai buttons enable
      enableAI(true);
      ppre=false;
    } catch (IOException ex){
      ex.printStackTrace();
      ppre=true;
    }
    
    
  }
  //save player
  private void PlayerSave(){
    try(BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(name.toString()+"Player.txt"), "UTF-8"))){
      for(int i=0;i<10;i++){
        for(int j=0;j<10;j++){
          writer.write(String.valueOf(bg.player[i][j]));
        }
        writer.write("\n");
      }
      writer.close();
    }catch (IOException ex){
      //handle me
      ex.printStackTrace();
    }
  }
  //load player
  private void PlayerLoad(){
    try (BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(name.toString()+"Player.txt"), "utf-8"))) {
      String temp;
      int counter=0;
      while((temp=reader.readLine())!=null){
        for(int j=0;j<10;j++){
          bg.player[counter][j]=temp.charAt(j);
          if(bg.player[counter][j]=='X'){
            buttons_Player[counter][j].setBackground(Color.red);
            buttons_Player[counter][j].setText(String.valueOf(bg.player[counter][j]));
          }
          else if(bg.player[counter][j]=='O'){
            buttons_Player[counter][j].setBackground(Color.yellow);
            buttons_Player[counter][j].setText(String.valueOf(bg.player[counter][j]));
          }
          else if(bg.player[counter][j]!=' '){
            buttons_Player[counter][j].setBackground(Color.gray);
            buttons_Player[counter][j].setText(String.valueOf(bg.player[counter][j]));
          }
        }
        counter++;
        System.out.println(temp);
        System.out.println(temp.length());
      }
      reader.close();
      //skip place ship part
      Tip.setText("Ready to fire!");

      //update button text
      fireButton.setText("Fire");
      ppre=false;
    } catch (IOException ex){
      ex.printStackTrace();
      Playerprepare();
      ppre=true;
    }
  }
  private void NameSave(){
//    try(BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("Name.txt"), "UTF-8"))){
//      writer.write(playerNameLabel.getText());
//      writer.close();
//    }catch (IOException ex){
//      //handle me
//      ex.printStackTrace();
//    }
  }
  //load name to player name label
  private void NameLoad(){
    playerNameLabel.setText(name);
//    try (BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream("Name.txt"), "utf-8"))) {
//      String temp;
//      temp=reader.readLine();
//      playerNameLabel.setText(temp);
//      System.out.println(temp);
//      System.out.println(temp.length());
//    reader.close();
//    } catch (IOException ex){
//      ex.printStackTrace();
//    }
  }
  public void reset(){
    File[] file = new File[3];
    String[] FileName = {name.toString()+"Player.txt", 
                         name.toString()+"AI.txt", 
                         name.toString()+"Name.txt"};
    for(int i=0;i<3;i++){
      file[i] = new File(FileName[i]);
      file[i].delete();
    }
  }
  //If true: username is unique, if false: username is already taken
    private boolean checkUsername(String username){
        results = 
         playerQueries.getPlayerByUsername(username);
        numberOfEntries = results.size();
        
        if (numberOfEntries <1 ){
          System.out.println("true");
            return true;
        } else{
          System.out.println("false");
            return false;
        }
        
    }
//  
//  public void startAILoad(){
//      
//  }
//   public void startPlayerLoad(){
//      
//  }
//  public void startNameLoad(){
//      
//  }
//   public void startUpdateTable(){
//      
//  }
  
}
